language: ruby
bundler_args: --without development
script: bundle exec rspec spec
env: JRUBY_OPTS="--server --debug -J-Xms512m -J-Xmx1024m"
rvm:
  - ruby-1.9.3
  - ruby-2.0.0
  - ruby-2.1.0
  - jruby-head
services:
  - redis-server
